# Generated by Django 5.2.7 on 2026-02-04 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="snapshot",
            name="error_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="snapshot",
            name="datapoints",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
